# Generated by Django 4.2.13 on 2024-06-29 20:41

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme', models.CharField(choices=[['BA', 'BA'], ['BCA', 'BCA'], ['BCom', 'BCom'], ['BEd', 'BEd'], ['BS', 'BS'], ['BSc', 'BSc'], ['Certificate', 'Certificate'], ['Diploma', 'Diploma'], ['MA', 'MA'], ['MCA', 'MCA'], ['MCom', 'MCom'], ['MSc', 'MSc'], ['MSW', 'MSW'], ['PG Diploma', 'PG Diploma'], ['PhD', 'PhD']], max_length=11)),
                ('Course', models.CharField(choices=[['English', 'English'], ['Journalism and Mass Communication', 'Journalism and Mass Communication'], ['Computer Applications', 'Computer Applications'], ['Data Science', 'Data Science'], ['Accounting & Finance', 'Accounting & Finance'], ['Commerce', 'Commerce'], ['Corporate Secretaryship', 'Corporate Secretaryship'], ['Finance and Taxation', 'Finance and Taxation'], ['Information System and Management', 'Information System and Management'], ['Professional Accounting', 'Professional Accounting'], ['Banking, Financial Services, and Insurance', 'Banking, Financial Services, and Insurance'], ['International Accounting & Finance', 'International Accounting & Finance'], ['Biological Science', 'Biological Science'], ['Commerce & Accounting', 'Commerce & Accounting'], ['Computer Science', 'Computer Science'], ['Economics', 'Economics'], ['Mathematics', 'Mathematics'], ['Physical Science', 'Physical Science'], ['Social Science', 'Social Science'], ['Tamil', 'Tamil'], ['Chemistry', 'Chemistry'], ['Hotel & Catering Management', 'Hotel & Catering Management'], ['Biotechnology', 'Biotechnology'], ['Computer Science Specialization in Cyber Security', 'Computer Science Specialization in Cyber Security'], ['Defence and Strategic Studies', 'Defence and Strategic Studies'], ['Fashion Designing', 'Fashion Designing'], ['Physical Education, Health Education and Sports', 'Physical Education, Health Education and Sports'], ['Psychology', 'Psychology'], ['Statistics', 'Statistics'], ['Visual Communication', 'Visual Communication'], ['Basic French', 'Basic French'], ['Certified Financial Management', 'Certified Financial Management'], ['Counter-Terrorism', 'Counter-Terrorism'], ['Financial Management', 'Financial Management'], ['Fire Fighting and Fire Safety', 'Fire Fighting and Fire Safety'], ['First Aid and Safety Management', 'First Aid and Safety Management'], ['Hotel Management and Catering Science', 'Hotel Management and Catering Science'], ['Yoga', 'Yoga'], ['Applied Data Science', 'Applied Data Science'], ['Organic Chemistry', 'Organic Chemistry'], ['Disaster Management', 'Disaster Management'], ['Master of Social Work', 'Master of Social Work'], ['Culinary Arts', 'Culinary Arts']], max_length=55)),
                ('Year', models.CharField(blank=True, choices=[['I', 'I'], ['II', 'II'], ['III', 'III']], max_length=3, null=True)),
                ('Section', models.CharField(blank=True, max_length=2, null=True)),
                ('Slot', models.CharField(blank=True, choices=[['A', 'A'], ['B', 'B']], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.CharField(max_length=15)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Order', models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]])),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=254)),
                ('EmpID', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=55)),
                ('Type', models.CharField(choices=[['Major', 'Major'], ['Elective', 'Elective']], max_length=8)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]])),
                ('Slot', models.CharField(choices=[['A', 'A'], ['B', 'B']], max_length=1)),
                ('Period', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('ClassRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classroom')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Absentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('StaffP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffp_absentees', to='app.staff')),
                ('Substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_absentees', to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Status', models.CharField(choices=[['PRESENT', 'PRESENT'], ['ABSENT', 'ABSENT']], max_length=7)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
