# Generated by Django 5.0.6 on 2024-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='Slot',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
