# Generated by Django 4.2.13 on 2024-06-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_absentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('StaffP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffp_absentees', to='app.staff')),
                ('Substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_absentees', to='app.staff')),
            ],
        ),
    ]
