# Generated by Django 4.2.13 on 2024-06-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_absentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentee',
            name='Substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_absentees', to='app.staff'),
        ),
    ]
