# Generated by Django 5.0.6 on 2024-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_class_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Section',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Slot',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Year',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=3, null=True),
        ),
    ]
