# Generated by Django 4.2.13 on 2024-06-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_absentee_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='SubPeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.period'),
        ),
    ]
