# Generated by Django 5.0.6 on 2024-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_class_section_alter_class_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Short',
        ),
        migrations.AlterField(
            model_name='class',
            name='Course',
            field=models.CharField(choices=[('English', 'English'), ('Journalism and Mass Communication', 'Journalism and Mass Communication'), ('Computer Applications', 'Computer Applications'), ('Data Science', 'Data Science'), ('Accounting & Finance', 'Accounting & Finance'), ('Commerce', 'Commerce'), ('Corporate Secretaryship', 'Corporate Secretaryship'), ('Finance and Taxation', 'Finance and Taxation'), ('Information System and Management', 'Information System and Management'), ('Professional Accounting', 'Professional Accounting'), ('Banking, Financial Services, and Insurance', 'Banking, Financial Services, and Insurance'), ('International Accounting & Finance', 'International Accounting & Finance'), ('Biological Science', 'Biological Science'), ('Commerce & Accounting', 'Commerce & Accounting'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Mathematics', 'Mathematics'), ('Physical Science', 'Physical Science'), ('Social Science', 'Social Science'), ('Tamil', 'Tamil'), ('Chemistry', 'Chemistry'), ('Hotel & Catering Management', 'Hotel & Catering Management'), ('Biotechnology', 'Biotechnology'), ('Computer Science Specialization in Cyber Security', 'Computer Science Specialization in Cyber Security'), ('Defence and Strategic Studies', 'Defence and Strategic Studies'), ('Fashion Designing', 'Fashion Designing'), ('Physical Education, Health Education and Sports', 'Physical Education, Health Education and Sports'), ('Psychology', 'Psychology'), ('Statistics', 'Statistics'), ('Visual Communication', 'Visual Communication'), ('Basic French', 'Basic French'), ('Certified Financial Management', 'Certified Financial Management'), ('Counter-Terrorism', 'Counter-Terrorism'), ('Financial Management', 'Financial Management'), ('Fire Fighting and Fire Safety', 'Fire Fighting and Fire Safety'), ('First Aid and Safety Management', 'First Aid and Safety Management'), ('Hotel Management and Catering Science', 'Hotel Management and Catering Science'), ('Yoga', 'Yoga'), ('Applied Data Science', 'Applied Data Science'), ('Organic Chemistry', 'Organic Chemistry'), ('Disaster Management', 'Disaster Management'), ('Master of Social Work', 'Master of Social Work'), ('Culinary Arts', 'Culinary Arts')], max_length=55),
        ),
        migrations.AlterField(
            model_name='class',
            name='Programme',
            field=models.CharField(choices=[('BA', 'BA'), ('BCA', 'BCA'), ('BCom', 'BCom'), ('BEd', 'BEd'), ('BS', 'BS'), ('BSc', 'BSc'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('MA', 'MA'), ('MCA', 'MCA'), ('MCom', 'MCom'), ('MSc', 'MSc'), ('MSW', 'MSW'), ('PG Diploma', 'PG Diploma'), ('PhD', 'PhD')], max_length=11),
        ),
    ]
