# Generated by Django 5.0.6 on 2024-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_class_short_alter_class_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='Period',
            field=models.IntegerField(),
        ),
    ]
