# Generated by Django 5.0.6 on 2024-06-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_period_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Type',
            field=models.CharField(choices=[('Major', 'Major'), ('Elective', 'Elective')], default='Major', max_length=8),
            preserve_default=False,
        ),
    ]
