# Generated by Django 4.2.13 on 2024-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='EmpID',
            field=models.CharField(default='Null', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='Course',
            field=models.CharField(choices=[['English', 'English'], ['Journalism and Mass Communication', 'Journalism and Mass Communication'], ['Computer Applications', 'Computer Applications'], ['Data Science', 'Data Science'], ['Accounting & Finance', 'Accounting & Finance'], ['Commerce', 'Commerce'], ['Corporate Secretaryship', 'Corporate Secretaryship'], ['Finance and Taxation', 'Finance and Taxation'], ['Information System and Management', 'Information System and Management'], ['Professional Accounting', 'Professional Accounting'], ['Banking, Financial Services, and Insurance', 'Banking, Financial Services, and Insurance'], ['International Accounting & Finance', 'International Accounting & Finance'], ['Biological Science', 'Biological Science'], ['Commerce & Accounting', 'Commerce & Accounting'], ['Computer Science', 'Computer Science'], ['Economics', 'Economics'], ['Mathematics', 'Mathematics'], ['Physical Science', 'Physical Science'], ['Social Science', 'Social Science'], ['Tamil', 'Tamil'], ['Chemistry', 'Chemistry'], ['Hotel & Catering Management', 'Hotel & Catering Management'], ['Biotechnology', 'Biotechnology'], ['Computer Science Specialization in Cyber Security', 'Computer Science Specialization in Cyber Security'], ['Defence and Strategic Studies', 'Defence and Strategic Studies'], ['Fashion Designing', 'Fashion Designing'], ['Physical Education, Health Education and Sports', 'Physical Education, Health Education and Sports'], ['Psychology', 'Psychology'], ['Statistics', 'Statistics'], ['Visual Communication', 'Visual Communication'], ['Basic French', 'Basic French'], ['Certified Financial Management', 'Certified Financial Management'], ['Counter-Terrorism', 'Counter-Terrorism'], ['Financial Management', 'Financial Management'], ['Fire Fighting and Fire Safety', 'Fire Fighting and Fire Safety'], ['First Aid and Safety Management', 'First Aid and Safety Management'], ['Hotel Management and Catering Science', 'Hotel Management and Catering Science'], ['Yoga', 'Yoga'], ['Applied Data Science', 'Applied Data Science'], ['Organic Chemistry', 'Organic Chemistry'], ['Disaster Management', 'Disaster Management'], ['Master of Social Work', 'Master of Social Work'], ['Culinary Arts', 'Culinary Arts']], max_length=55),
        ),
        migrations.AlterField(
            model_name='class',
            name='Programme',
            field=models.CharField(choices=[['BA', 'BA'], ['BCA', 'BCA'], ['BCom', 'BCom'], ['BEd', 'BEd'], ['BS', 'BS'], ['BSc', 'BSc'], ['Certificate', 'Certificate'], ['Diploma', 'Diploma'], ['MA', 'MA'], ['MCA', 'MCA'], ['MCom', 'MCom'], ['MSc', 'MSc'], ['MSW', 'MSW'], ['PG Diploma', 'PG Diploma'], ['PhD', 'PhD']], max_length=11),
        ),
        migrations.AlterField(
            model_name='class',
            name='Slot',
            field=models.CharField(blank=True, choices=[['A', 'A'], ['B', 'B']], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Year',
            field=models.CharField(blank=True, choices=[['I', 'I'], ['II', 'II'], ['III', 'III']], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dayorder',
            name='Order',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]]),
        ),
        migrations.AlterField(
            model_name='period',
            name='Order',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]]),
        ),
        migrations.AlterField(
            model_name='period',
            name='Slot',
            field=models.CharField(choices=[['A', 'A'], ['B', 'B']], max_length=1),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='Status',
            field=models.CharField(choices=[['PRESENT', 'PRESENT'], ['ABSENT', 'ABSENT']], max_length=7),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Type',
            field=models.CharField(choices=[['Major', 'Major'], ['Elective', 'Elective']], max_length=8),
        ),
    ]
