# Generated by Django 4.2.13 on 2024-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_staff_empid_alter_class_course_alter_class_programme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='Department',
        ),
        migrations.AddField(
            model_name='staff',
            name='Department',
            field=models.CharField(default='Computer Science', max_length=75),
            preserve_default=False,
        ),
    ]
